# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4857a18f3e1510b7845249f93e313bd967b198f35a567c1aec06af8a72c6e4d02d9169adefa97b2cfb2648a372018f7824b19f92e6d6ac5dc7718718bac6b600

test:
  secret_key_base: 7e32ce2b7f3191210c688559b38ad4cc767136f84a887fed1e197b7b05601c32b67ad8e150ceb72c32c754a3dede17a6ac04577e2fce4e4e7a5f2744c51c8965

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
